# Generated by Django 4.0.4 on 2022-05-03 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('image', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('video', models.CharField(max_length=70)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Power_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intelligence', models.PositiveBigIntegerField()),
                ('strength', models.PositiveBigIntegerField()),
                ('speed', models.PositiveBigIntegerField()),
                ('durability', models.PositiveBigIntegerField()),
                ('power', models.PositiveBigIntegerField()),
                ('combat', models.PositiveBigIntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heroes_api.hero')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=70)),
                ('info', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='heroes_api.hero')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
