# Generated by Django 4.0.4 on 2022-05-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes_api', '0002_alter_power_stats_combat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='logos'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='image',
            field=models.ImageField(upload_to='character'),
        ),
    ]
